#!/bin/bash

set -e

if [ -n "$(git status --porcelain)" ];
then
    git status
    echo "Uncommitted changes. Exiting."
    exit 1
fi

rm -rf node_modules
git clean -fdx
npm install
npm run prepare
npm run lint
npm run test

npm pack
tar tvzf netinsight-sye-tools*
rm netinsight-sye-tools*

echo "Do you want to publish this version?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) echo "Publishing"; break;;
        No ) exit;;
    esac
done
